# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI+PhoneNumberKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PhoneNumberKit'
  # Pods for SwiftUI+PhoneNumberKit

  target 'SwiftUI+PhoneNumberKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUI+PhoneNumberKitUITests' do
    # Pods for testing
  end

end
